# itk-version: 1.0.1
version: "3"

networks:
  app:
    driver: bridge
    internal: false

services:
  phpfpm:
    image: itkdev/php8.0-fpm:latest
    networks:
      - app
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - COMPOSER_VERSION=2
    volumes:
      - .:/app:delegated
